### PR TITLE
Release 0.23.0

### PR DESCRIPTION
**Pull request by robin-checkmk**
## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: `e.g. #1` 

## What is the new behavior?

- #318
- #341

### CODE REVIEW

**Comment by robin-checkmk** [comment]
@msekania it looks like you used an email address for your commits, that is not associated with your account. Can you please look into the linked article, to see if you can fix that? If you need help, do let me know. :v:

**Comment by msekania** [comment]
Is it better now?

**Comment by msekania** [comment]
@robin-checkmk
I have added second e-mail address to my account, but I do not see any blue circled question mark like it is described in "To read a message about why the commit is not linked, hover over the blue to the right of the username."

**Comment by robin-checkmk** [comment]
recheck

**Comment by msekania** [comment]
@robin-checkmk,

How does it work, I think I have followed the described steps, but still get an error

**Comment by robin-checkmk** [comment]
@msekania you need to post the following statement as a comment here, to confirm, that you agree to the CLA.

> I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by msekania** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by msekania** [comment]
@robin-checkmk 

one should make readme fro CLA more clear.

**Comment by robin-checkmk** [comment]
Everyone that was mentioned by the CLA Bot but did not contribute to this PR: I apologize for the inconvenience! I had to perform some git-magic, that went sideways. If you could just sign the CLA real quick, that would be great!

For those, where the bot did not find a GitHub account: Please follow the linked guide. That would be:
- @lgetwan 
- @geof77 

If there are any questions, do let me know.

**Comment by Max-checkmk** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by englertor** [comment]
recheck

**Comment by Lars** [comment]
If so, the bot will fail if I include any other text than the aforementioned line in the message? As I want to make clear I or my organization have not contributed any work to this push and I have not signed a CLA with this project.

**Comment by robin-checkmk** [comment]
> I'm sorry if I'm misunderstanding, you're requesting I sign the CLA in the name of somebody else for the PR to go through even though I have taken no part of this PR?

Hi @Lars and sorry for the misunderstanding.
Of course, you should not sign anything here, you were mentioned by the bot on accident. Please just ignore this, we are trying to clean things up. The same goes for @Geoffroy of course.

**Comment by lgetwan** [comment]
I have read the CLA Document and I hereby sign the CLA or my organization already has a signed CLA.

**Comment by robin-checkmk** [comment]
Hi everyone!

Once again apologies for the noise and potential confusion in this PR!
I will be off for two weeks now and will merge this PR after my return.
It would be lovely to see missing signatures by then. Thanks!

See you in roughly two weeks!

**Review by lgetwan — APPROVED** [review]
Most code changes have been reviewed by me when merged into the devel branch.
I just checked the rest of the changes for consistency.

**Pull request merged**
